"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import Callable, List
from neuropy.utils.mixins.print_helpers import SimplePrintable

class KnownDataSessionTypeProperties(SimplePrintable):
    """ KnownDataSessionTypeProperties describes the specific stages required to load a DataSession for a specific type. """
    load_function: Callable
    basedir: Path
    post_load_functions: List[Callable]
    filter_functions: List[Callable]
    post_compute_functions: List[Callable]
    def __init__(self, load_function: Callable, basedir: Path, post_load_functions: List[Callable] = ..., filter_functions: List[Callable] = ..., post_compute_functions: List[Callable] = ...) -> None:
        ...
    


