name: NeuroPy
channels:
    - conda-forge
dependencies:
    - python=3.9
    - numpy=1.20.2
    - scipy=1.6.2
    - matplotlib
    - pandas
    - joblib
    - scikit-learn
    - hmmlearn
    - ipywidgets
    - seaborn
    - opencv
    - pytables
    # - cupy  # uncomment this if you want to run correlograms with a GPU.
    
    # Works well in RedHat8. Note you may have to comment out the following lines and then install manually "pip install scikit-posthocs" in Windows.
    - pip:
      - scikit-posthocs
