name: NeuroPy
channels:
    - conda-forge
dependencies:
    - python=3.8
    - numpy=1.19.1
    - scipy=1.5.2
    - matplotlib
    - pandas
    - joblib
    - scikit-learn
    - hmmlearn
    - ipywidgets
    - seaborn
    # Works well in linux. Note you may have to comment out the following lines and then install manually "pip install scikit-posthocs" in Windows.
    - pip:
	- scikit-posthocs
