"""
This type stub file was generated by pyright.
"""

from typing import Dict, List
from neuropy.core.session.Formats.SessionSpecifications import ParametersContainer
from neuropy.utils.dynamic_container import DynamicContainer
from neuropy.utils.result_context import IdentifyingContext

def find_local_session_paths(local_session_parent_path, exclude_list=..., debug_print=...): # -> tuple[list[Any] | None, list[Any] | None]:
	"""Finds the local session paths

	History: From PendingNotebookCode's 2022-12-07 section - "Finding Local Session Paths"

	Args:
		local_session_parent_path (_type_): _description_
		exclude_list (list, optional): _description_. Defaults to [].
		debug_print (bool, optional): _description_. Defaults to True.

	Returns:
		_type_: _description_

	History: extracted from PendingNotebookCode on 2022-12-13 from section "2022-12-07 - Finding Local Session Paths"

	Usage:

		from neuropy.core.session.Formats.BaseDataSessionFormats import find_local_session_paths

		active_data_mode_name = 'kdiba'
		local_session_root_parent_context = IdentifyingContext(format_name=active_data_mode_name)
		local_session_root_parent_path = global_data_root_parent_path.joinpath('KDIBA')

		## Animal `gor01`:
		local_session_parent_context = local_session_root_parent_context.adding_context(collision_prefix='animal', animal='gor01', exper_name='one')
		local_session_parent_path = local_session_root_parent_path.joinpath(local_session_parent_context.animal, local_session_parent_context.exper_name)
		local_session_paths_list, local_session_names_list =  find_local_session_paths(local_session_parent_path, exclude_list=['PhoHelpers', 'Spike3D-Minimal-Test', 'Unused'])

	>>> local_session_names_list: ['2006-6-07_11-26-53', '2006-6-08_14-26-15', '2006-6-09_1-22-43', '2006-6-09_3-23-37', '2006-6-12_15-55-31', '2006-6-13_14-42-6']
		local_session_paths_list: {WindowsPath('W:/Data/KDIBA/gor01/one/2006-6-07_11-26-53'): <SessionBatchProgress.NOT_STARTED: 'NOT_STARTED'>,
			WindowsPath('W:/Data/KDIBA/gor01/one/2006-6-08_14-26-15'): <SessionBatchProgress.NOT_STARTED: 'NOT_STARTED'>,
			WindowsPath('W:/Data/KDIBA/gor01/one/2006-6-09_1-22-43'): <SessionBatchProgress.NOT_STARTED: 'NOT_STARTED'>,
			WindowsPath('W:/Data/KDIBA/gor01/one/2006-6-09_3-23-37'): <SessionBatchProgress.NOT_STARTED: 'NOT_STARTED'>,
			WindowsPath('W:/Data/KDIBA/gor01/one/2006-6-12_15-55-31'): <SessionBatchProgress.NOT_STARTED: 'NOT_STARTED'>,
			WindowsPath('W:/Data/KDIBA/gor01/one/2006-6-13_14-42-6'): <SessionBatchProgress.NOT_STARTED: 'NOT_STARTED'>}
	"""
	...

class DataSessionFormatRegistryHolder(type):
	""" a metaclass that automatically registers its conformers as a known loadable data session format.
		
	Usage:
		from neuropy.core.session.Formats.BaseDataSessionFormats import DataSessionFormatRegistryHolder
		from neuropy.core.session.Formats.Specific.BapunDataSessionFormat import BapunDataSessionFormatRegisteredClass
		from neuropy.core.session.Formats.Specific.KDibaOldDataSessionFormat import KDibaOldDataSessionFormatRegisteredClass
		from neuropy.core.session.Formats.Specific.RachelDataSessionFormat import RachelDataSessionFormat
		from neuropy.core.session.Formats.Specific.HiroDataSessionFormat import HiroDataSessionFormatRegisteredClass

		DataSessionFormatRegistryHolder.get_registry()
		
	"""
	REGISTRY: Dict[str, DataSessionFormatRegistryHolder] = ...
	def __new__(cls, name, bases, attrs): # -> Self:
		...
	
	@classmethod
	def get_registry(cls): # -> dict[str, DataSessionFormatRegistryHolder]:
		...
	
	@classmethod
	def get_registry_data_session_type_class_name_dict(cls): # -> dict[Any, DataSessionFormatRegistryHolder]:
		""" returns a dict<str, DataSessionFormatBaseRegisteredClass> with keys corresponding to the registered short-names of the data_session_type (like 'kdiba', or 'bapun') and values of DataSessionFormatBaseRegisteredClass. """
		...
	
	@classmethod
	def get_registry_known_data_session_type_dict(cls, override_data_basepath=..., override_parameters_flat_keypaths_dict=...): # -> dict[Any, Any]:
		""" returns a dict<str, KnownDataSessionTypeProperties> with keys corresponding to the registered short-names of the data_session_type (like 'kdiba', or 'bapun') and values of KnownDataSessionTypeProperties. """
		...
	


class DataSessionFormatBaseRegisteredClass(metaclass=DataSessionFormatRegistryHolder):
	"""
	Any class that will inherit from DataSessionFormatBaseRegisteredClass will be included
	inside the dict RegistryHolder.REGISTRY, the key being the name of the
	class and the associated value, the class itself.
	
	The user specifies a basepath, which is the path containing a list of files:
	
	📦Day5TwoNovel
	 ┣ 📜RatS-Day5TwoNovel-2020-12-04_07-55-09.eeg
	 ┣ 📜RatS-Day5TwoNovel-2020-12-04_07-55-09.mua.npy
	 ┣ 📜RatS-Day5TwoNovel-2020-12-04_07-55-09.neurons.npy
	 ┣ 📜RatS-Day5TwoNovel-2020-12-04_07-55-09.paradigm.npy
	 ┣ 📜RatS-Day5TwoNovel-2020-12-04_07-55-09.pbe.npy
	 ┣ 📜RatS-Day5TwoNovel-2020-12-04_07-55-09.position.npy
	 ┣ 📜RatS-Day5TwoNovel-2020-12-04_07-55-09.probegroup.npy
	 ┣ 📜RatS-Day5TwoNovel-2020-12-04_07-55-09.ripple.npy
	 ┗ 📜RatS-Day5TwoNovel-2020-12-04_07-55-09.xml
	
	
	By default it attempts to find the single *.xml file in the root of this basedir, from which it determines the `session_name` as the stem (the part before the extension) of this file:
		basedir: Path(r'R:\data\Bapun\Day5TwoNovel')
		session_name: 'RatS-Day5TwoNovel-2020-12-04_07-55-09'
	
	From here, a list of known files to load from is determined:
		
	"""
	_session_class_name = ...
	_session_default_relative_basedir = ...
	_session_default_basedir = ...
	_time_variable_name = ...
	@classmethod
	def get_session_format_name(cls): # -> str:
		""" The name of the specific format (e.g. 'bapun', 'kdiba', etc) """
		...
	
	@classmethod
	def get_session_name(cls, basedir):
		""" MUST be overriden by implementor to return the session_name for this basedir, which determines the files to load. """
		...
	
	@classmethod
	def get_session_spec(cls, session_name):
		""" MUST be overriden by implementor to return the a session_spec """
		...
	
	@classmethod
	def build_global_epoch_filter_config_dict(cls, sess, global_epoch_name=..., first_included_epoch_name=..., last_included_epoch_name=..., filter_name_suffix=..., debug_print=...): # -> tuple[dict[str, Callable[..., tuple[Any, NamedTimerange, Any]]], NamedTimerange]:
		""" builds the 'global' filter for the entire session that includes by default the times from all other epochs in sess. 
		e.g. builds the 'maze' epoch from ['maze1', 'maze2'] epochs

		Usage:
			global_epoch_filter_fn_dict, global_named_timerange = build_global_epoch_filter_config_dict(sess, global_epoch_name='maze', first_included_epoch_name=None, last_included_epoch_name=None, debug_print=True)
			global_epoch_filter_fn_dict

		"""
		...
	
	@classmethod
	def build_default_filter_functions(cls, sess, epoch_name_includelist=..., filter_name_suffix=..., include_global_epoch=...): # -> dict[str, Callable[..., tuple[Any, Any, Any]]]:
		""" OPTIONALLY can be overriden by implementors to provide specific filter functions
		Inputs:
			epoch_name_includelist: an optional list of names to restrict to, must already be valid epochs to filter by. e.g. ['maze1']
			filter_name_suffix: an optional string suffix to be added to the end of each filter_name. An example would be '_PYR'
			include_global_epoch: bool - If True, uses cls.build_global_epoch_filter_config_dict(...) to generate a global epoch that will be included in the filters
		"""
		...
	
	@classmethod
	def build_default_preprocessing_parameters(cls, **kwargs) -> ParametersContainer:
		""" builds the pre-processing parameters. Could get session_spec, basedir, or other info from the caller but usually not a session itself because this is used to build the config prior to the session loading. 
		
		Used in: ['cls.build_session']
		"""
		...
	
	@classmethod
	def build_default_computation_configs(cls, sess, **kwargs) -> List[DynamicContainer]:
		""" OPTIONALLY can be overriden by implementors to provide specific filter functions """
		...
	
	@classmethod
	def build_active_computation_configs(cls, sess, **kwargs): # -> List[DynamicContainer]:
		""" defines the main computation configs for each class. This is provided as an alternative to `build_default_computation_configs` because some classes use cls.build_default_computation_configs(...) to get the plain configs, which they then update with different properties. """
		...
	
	@classmethod
	def get_session(cls, basedir, override_parameters_flat_keypaths_dict=...):
		...
	
	@classmethod
	def find_session_name_from_sole_xml_file(cls, basedir, debug_print=...):
		""" By default it attempts to find the single *.xml file in the root of this basedir, from which it determines the `session_name` as the stem (the part before the extension) of this file
		Example:
			basedir: Path(r'R:\data\Bapun\Day5TwoNovel')
			session_name: 'RatS-Day5TwoNovel-2020-12-04_07-55-09'
		"""
		...
	
	@classmethod
	def get_session_basepath_to_context_parsing_keys(cls):
		""" Just a wrapper to access the cls._session_basepath_to_context_parsing_keys property
		Used only by `parse_session_basepath_to_context(.)`
		"""
		...
	
	@classmethod
	def parse_session_basepath_to_context(cls, basedir) -> IdentifyingContext:
		""" parses the session's path to determine its proper context. Depends on the data_type.
		finds global_data_root

		USED: Called only in `cls.build_session(.)`

		KDIBA: 'W:/Data/KDIBA/gor01/one/2006-6-09_3-23-37' | context_keys = ['format_name','animal','exper_name', 'session_name']
		HIRO: 'W:/Data/Hiro/RoyMaze1' | context_keys = ['format_name', 'session_name']
			# Additional parsing needed: W:\Data\Hiro\RoyMaze2

		BAPUN: 'W:/Data/Bapun/RatS/Day5TwoNovel' | context_keys = ['format_name','animal', 'session_name']
		RACHEL: 'W:/Data/Rachel/merged_M1_20211123_raw_phy' | context_keys = ['format_name', 'session_name']

		"""
		...
	
	@classmethod
	def get_known_data_session_type_properties(cls, override_basepath=..., override_parameters_flat_keypaths_dict=...): # -> KnownDataSessionTypeProperties:
		""" returns the KnownDataSessionTypeProperties for this class, which contains information about the process of loading the session."""
		...
	
	@classmethod
	def build_session(cls, basedir, override_parameters_flat_keypaths_dict=...): # -> DataSession:
		...
	
	@classmethod
	def load_session(cls, session, debug_print=...): # -> tuple[Any, list[Any]]:
		...
	
	@classmethod
	def compute_position_grid_bin_size(cls, x, y, num_bins=..., debug_print=...): # -> tuple[Any, ...]:
		""" Compute Required Bin size given a desired number of bins in each dimension
		Usage:
			active_grid_bin = compute_position_grid_bin_size(curr_kdiba_pipeline.sess.position.x, curr_kdiba_pipeline.sess.position.y, num_bins=(64, 64)
		"""
		...
	


