"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from attrs import define
from typing import Callable, Dict, Optional, Tuple
from pathlib import Path
from neuropy.core.session.dataSession import DataSession
from neuropy.utils.mixins.print_helpers import OrderedMeta, SimplePrintable
from neuropy.utils.result_context import IdentifyingContext
from neuropy.core.parameters import ParametersContainer

@dataclass
class SessionFileSpec:
    """ Specifies a specification for a single file.
    Members:
        session_load_callback: Callable[[Path, DataSession], DataSession] a function that takes the path to load and the session to load it into and performs the operation
    
    Examples: 
        SessionFileSpec('{}.xml', session_name, 'The primary .xml configuration file'), SessionFileSpec('{}.neurons.npy', session_name, 'The numpy data file containing information about neural activity.')
        SessionFileSpec('{}.probegroup.npy', session_name, 'The numpy data file containing information about the spatial layout of recording probes')
        SessionFileSpec('{}.position.npy', session_name, 'The numpy data file containing the recorded animal positions (as generated by optitrack) over time.')
        SessionFileSpec('{}.paradigm.npy', session_name, 'The numpy data file containing the recording epochs. Each epoch is defined as a: (label:str, t_start: float (in seconds), t_end: float (in seconds))')
    """
    fileSpecString: str
    suggestedBaseName: str
    description: str
    session_load_callback: Callable[[Path, DataSession], DataSession]
    @property
    def filename(self): # -> str:
        """The filename property."""
        ...
    
    def resolved_path(self, parent_path, overrideBasename=...):
        """Gets the resolved Path given the parent_path """
        ...
    


class SessionFolderSpecError(Exception):
    """ An exception raised when a session folder spec requirement fails """
    def __init__(self, message, failed_spec_item) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


class RequiredFileError(SessionFolderSpecError):
    """ An exception raised when a required file is missing """
    def __init__(self, message, missing_file_spec) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


class RequiredValidationFailedError(SessionFolderSpecError):
    """ An exception raised when a required validation spec fails """
    def __init__(self, message, failed_validation) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


class SessionFolderSpec:
    """ Documents the required and optional files for a given session format """
    def __init__(self, required=..., optional=..., additional_validation_requirements=...) -> None:
        ...
    
    def __repr__(self) -> str:
        ...
    
    def resolved_paths(self, proposed_session_path): # -> tuple[dict[Any, Any], dict[Any, Any]]:
        """ Gets whether the proposed_session_path meets the requirements and returns the resolved paths if it can.
            Does not check whether any of the files exist, it just builds the paths
            
        Returns:
            two dictionaries containing the resolved path:file_spec pairs
        """
        ...
    
    def validate(self, proposed_session_path): # -> tuple[bool, dict[Any, Any], dict[Any, Any]]:
        """Check whether the proposed_session_path meets this folder spec's requirements
        Args:
            proposed_session_path ([Path]): [description]

        Returns:
            [Bool]: [description]
        """
        ...
    


@define(slots=False, repr=False, str=False)
class SessionConfig(SimplePrintable, metaclass=OrderedMeta):
    """A simple data structure that holds the information specifying a data session, such as the basepath, session_spec, and session_name
    
    TODO 2023-10-23 - Upgrade to attrs class
    
    
    from neuropy.core.session.Formats.SessionSpecifications import SessionConfig
    
    """
    basepath: Path = ...
    session_spec: SessionFolderSpec = ...
    session_name: str = ...
    session_context: IdentifyingContext = ...
    format_name: str = ...
    preprocessing_parameters: ParametersContainer = ...
    absolute_start_timestamp: float = ...
    position_sampling_rate_Hz: float = ...
    microseconds_to_seconds_conversion_factor: float = ...
    pix2cm: float = ...
    x_midpoint: float = ...
    loaded_track_limits: dict = ...
    grid_bin_bounds: Optional[Tuple[Tuple[float, float], Tuple[float, float]]] = ...
    real_unit_grid_bin_bounds: Optional[Tuple[Tuple[float, float], Tuple[float, float]]] = ...
    real_cm_grid_bin_bounds: Optional[Tuple[Tuple[float, float], Tuple[float, float]]] = ...
    grid_bin_bin: Optional[Tuple[float, float]] = ...
    track_start_t: Optional[float] = ...
    track_end_t: Optional[float] = ...
    is_resolved: bool = ...
    resolved_required_filespecs_dict: dict = ...
    resolved_optional_filespecs_dict: dict = ...
    additional_metadata: Dict = ...
    @property
    def resolved_required_file_specs(self): # -> dict[Any, Callable[..., Any]]:
        """The resolved_required_file_specs property."""
        ...
    
    @property
    def resolved_optional_file_specs(self): # -> dict[Any, Callable[..., Any]]:
        """The resolved_required_file_specs property."""
        ...
    
    def __attrs_post_init__(self): # -> None:
        ...
    
    def validate(self): # -> None:
        """ re-validates the self.session_spec items and updates the resolved dicts """
        ...
    
    def to_dict(self): # -> dict[str, str]:
        ...
    
    def get_context(self): # -> IdentifyingContext:
        """ returns an IdentifyingContext for the session """
        ...
    
    def get_description(self, prefix_items=...) -> str:
        """ returns a simple text descriptor of the session
        Outputs:
            a str like 'sess_kdiba_2006-6-07_11-26-53'
        """
        ...
    
    def __str__(self) -> str:
        ...
    
    def __getstate__(self): # -> dict[str, Any]:
        ...
    
    def __setstate__(self, state): # -> None:
        ...
    


