"""
This type stub file was generated by pyright.
"""

from typing import Dict
from attr import define
from neuropy.utils.mixins.gettable_mixin import GetAccessibleMixin, KeypathsAccessibleMixin
from neuropy.utils.mixins.AttrsClassHelpers import AttrsBasedClassHelperMixin
from neuropy.utils.mixins.HDF5_representable import HDF_SerializationMixin

@define(slots=False)
class BaseConfig(KeypathsAccessibleMixin, GetAccessibleMixin):
    """ 2023-10-24 - Base class to enable successful unpickling from old pre-attrs-based classes (based on `DynamicParameters`) to attrs-based classes.`

    from neuropy.core.parameters import BaseConfig
    
    History: 2024-10-23 11:36 Refactored from {pyphoplacecellanalysis.General.Model.Configs.DynamicConfigs.BaseConfig}
    
    """
    def __getstate__(self): # -> dict[str, Any]:
        ...
    
    def __setstate__(self, state): # -> None:
        ...
    
    def get(self, attribute_name, default=...): # -> Any | None:
        """ Use the getattr built-in function to retrieve attributes """
        ...
    


@define(slots=False, repr=False, eq=False)
class ParametersContainer(HDF_SerializationMixin, AttrsBasedClassHelperMixin, BaseConfig):
    """ 
    from neuropy.core.parameters import ParametersContainer
    
	from neuropy.core.session.Formats.BaseDataSessionFormats.ParametersContainer
    from neuropy.core.session.Formats.BaseDataSessionFormats import ParametersContainer
    
    """
    epoch_estimation_parameters: dict = ...
    def to_dict(self) -> Dict:
        ...
    
    def __repr__(self): # -> str:
        """ 2024-01-11 - Renders only the fields and their sizes  """
        ...
    
    def to_hdf(self, file_path, key: str, **kwargs): # -> None:
        """ Saves the object to key in the hdf5 file specified by file_path"""
        ...
    


