"""
This type stub file was generated by pyright.
"""

def import_mat_file(mat_import_file=..., debug_print: bool = ...): # -> dict[Any, Any]:
    ...

def find_session_xml(local_session_path, debug_print=...): # -> tuple[Path | Any, str | Any, Path | Any]:
    """finds the XML file for a given session provided the session folder path

    Args:
        local_session_path (_type_): _description_

    Usage:
        from neuropy.utils.load_exported import find_session_xml

        # local_session_path = Path(r'W:\Data\KDIBA\gor01\one\2006-6-08_14-26-15')
        # local_session_path = Path(r'W:\Data\KDIBA\gor01\one\2006-6-08_14-26-15')
        local_session_path, session_stem, local_session_path = Path(r'W:\Data\KDIBA\gor01\one\2006-6-13_14-42-6')

        session_xml_filepath = find_session_xml(local_session_path)
        out_xml_dict, d = LoadXml(session_xml_filepath)
        print(f"active_shank_channels_lists: {out_xml_dict['AnatGrps']}")

    """
    ...

def LoadXml(session_xml_filepath, MAX_CHANNEL_GROUP_LENGTH=..., debug_print=...): # -> tuple[dict[str, int | benedict | Any], benedict]:
    """ Based off of the MATLAB code `load_files\LoadXml.m`
    Usage:
        session_xml_filepath = Path(r'W:\Data\KDIBA\gor01\one\2006-6-08_14-26-15\2006-6-08_14-26-15.xml')
        assert session_xml_filepath.exists() and session_xml_filepath.is_file()
        out_xml_dict, d = LoadXml(session_xml_filepath)
        out_xml_dict
    """
    ...

