"""
This type stub file was generated by pyright.
"""

import pandas as pd
from datetime import datetime
from typing import Dict, List, Optional, Tuple
from pathlib import Path
from neuropy.core.session.Formats.BaseDataSessionFormats import DataSessionFormatBaseRegisteredClass
from neuropy.core.session.dataSession import DataSession
from neuropy.core.session.Formats.SessionSpecifications import SessionFolderSpec
from neuropy.utils.result_context import IdentifyingContext

class KDibaOldDataSessionFormatRegisteredClass(DataSessionFormatBaseRegisteredClass):
    """
    
    By default it attempts to find the single *.xml file in the root of this basedir, from which it determines the `session_name` as the stem (the part before the extension) of this file:
        basedir: Path('R:\data\KDIBA\gor01\one\2006-6-07_11-26-53')
        session_name: '2006-6-07_11-26-53'
    
    # Example Filesystem Hierarchy:
    📦gor01
    ┣ 📂one
    ┃ ┣ 📂2006-6-07_11-26-53
    ┃ ┃ ┣ 📂bak
    ┃ ┃ ┃ ┣ 📜2006-6-07_11-26-53.pbe.npy
    ┃ ┃ ┃ ┗ 📜2006-6-07_11-26-53.mua.npy
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.eeg
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.epochs_info.mat
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.fet.1
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.fet.10
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.fet.11
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.fet.12
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.fet.2
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.fet.3
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.fet.4
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.fet.5
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.fet.6
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.fet.7
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.fet.8
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.fet.9
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.interpolated_spike_positions.npy     <-OPT-GEN
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.laps_info.mat
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.nrs
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.position.npy
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.position_info.mat
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.res.1
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.res.10
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.res.11
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.res.12
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.res.2
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.res.3
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.res.4
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.res.5
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.res.6
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.res.7
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.res.8
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.res.9
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.rpl.evt
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.seq.evt
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.session.mat
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.spikeII.mat
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.spikes.cellinfo.mat
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.spikes.mat
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.spk.1
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.spk.10
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.spk.11
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.spk.12
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.spk.2
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.spk.3
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.spk.4
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.spk.5
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.spk.6
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.spk.7
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.spk.8
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.spk.9
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.swr.evt
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.theta.1
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.whl
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.xml
    ┃ ┃ ┣ 📜2006-6-07_11-26-53IN.5.res
    ┃ ┃ ┣ 📜2006-6-07_11-26-53vt.mat
    ┃ ┃ ┣ 📜Events.Nev
    ┃ ┃ ┣ 📜RippleDatabase.mat
    ┃ ┃ ┣ 📜VT1.Nvt
    ┃ ┃ ┣ 📜data_NeuroScope2.mat
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.ripple.npy
    ┃ ┃ ┣ 📜2006-6-07_11-26-53.mua.npy
    ┃ ┃ ┗ 📜2006-6-07_11-26-53.pbe.npy
    ┃ ┣ 📜IIdata.mat
 
    From here, a list of known files to load from is determined:
        
    Usage:
    
        from neuropy.core.session.Formats.BaseDataSessionFormats import DataSessionFormatRegistryHolder, DataSessionFormatBaseRegisteredClass
        from neuropy.core.session.Formats.Specific.KDibaOldDataSessionFormat import KDibaOldDataSessionFormatRegisteredClass
        
        _test_session = KDibaOldDataSessionFormatRegisteredClass.build_session(Path(r'R:\data\KDIBA\gor01\one\2006-6-07_11-26-53'))
        _test_session, loaded_file_record_list = KDibaOldDataSessionFormatRegisteredClass.load_session(_test_session)
        _test_session

    """
    _session_class_name: str = ...
    _session_default_relative_basedir: str = ...
    _session_default_basedir: str = ...
    _session_basepath_to_context_parsing_keys: list[str] = ...
    _time_variable_name: str = ...
    @classmethod
    def get_specific_session_override_dict(cls) -> dict:
        ...
    
    @classmethod
    def get_known_data_session_type_properties(cls, override_basepath=..., override_parameters_flat_keypaths_dict=...): # -> KnownDataSessionTypeProperties:
        """ returns the session_name for this basedir, which determines the files to load. """
        ...
    
    @classmethod
    def POSTLOAD_estimate_laps_and_replays(cls, sess):
        """ a POSTLOAD function: after loading, estimates the laps and replays objects (replacing those loaded). """
        ...
    
    @classmethod
    def build_filters_pyramidal_epochs(cls, sess, epoch_name_includelist=..., filter_name_suffix=...): # -> dict[str, Any]:
        ...
    
    @classmethod
    def build_filters_any_maze_epochs(cls, sess): # -> dict[str, Callable[..., tuple[Any, NamedTimerange, Any]]]:
        ...
    
    @classmethod
    def build_default_filter_functions(cls, sess, epoch_name_includelist=..., filter_name_suffix=..., include_global_epoch=...): # -> dict[str, Callable[..., tuple[Any, Any, Any]]]:
        ...
    
    @classmethod
    def build_lap_only_computation_configs(cls, sess, **kwargs): # -> list[Any]:
        """ sets the computation intervals to only be performed on the laps """
        ...
    
    @classmethod
    def build_lap_only_short_long_bin_aligned_computation_configs(cls, sess, **kwargs): # -> list[Any]:
        """ 2023-05-16 - sets the computation intervals to only be performed on the laps """
        ...
    
    @classmethod
    def build_default_computation_configs(cls, sess, **kwargs): # -> List[DynamicContainer]:
        """ _get_computation_configs(curr_kdiba_pipeline.sess) 
            # From Diba:
            # (3.777, 1.043) # for (64, 64) bins
            # (1.874, 0.518) # for (128, 128) bins
        """
        ...
    
    @classmethod
    def build_active_computation_configs(cls, sess, **kwargs): # -> list[Any]:
        ...
    
    @classmethod
    def get_session_name(cls, basedir): # -> str:
        """ returns the session_name for this basedir, which determines the files to load. """
        ...
    
    @classmethod
    def get_session_spec(cls, session_name) -> SessionFolderSpec:
        ...
    
    @classmethod
    def load_session(cls, session, debug_print=...): # -> tuple[Any, list[Any]]:
        ...
    
    @classmethod
    def parse_session_dates(cls, dates: List[str]) -> List[datetime]:
        """ parses the session_name to a datetime, adding the year (2006) as needed. 
        """
        ...
    
    @classmethod
    def build_session_basedirs_dict(cls, global_data_root_parent_path, debug_print=...) -> Dict[IdentifyingContext, Path]:
        """ generates a dict of session_ctx:basedir. Hardcoded for the KDIBA sessions.
        
        Does not check for existance of the basedirs

        History: 2023-09-21 - Extracted from `pyphoplacecellanalysis.General.Batch.runBatch.run_diba_batch`
        
        Usage:
        
            ## Find all existing sessions:
            assert global_data_root_parent_path.exists(), f"global_data_root_parent_path: {global_data_root_parent_path} does not exist! Is the right computer's config commented out above?"
            active_data_mode_name = 'kdiba'
            output_session_basedir_dict = KDibaOldDataSessionFormatRegisteredClass.build_session_basedirs_dict(global_data_root_parent_path)
            ## OUTPUTS: output_session_basedir_dict
            output_session_basedir_dict

            for curr_session_context, curr_session_basedir in output_session_basedir_dict.items():
                print(f'EXTANT SESSION! curr_session_context: {curr_session_context}, curr_session_basedir: {curr_session_basedir}')


        """
        ...
    
    @classmethod
    def find_all_existing_sessions(cls, global_data_root_parent_path: Path) -> pd.DataFrame:
        """ discovers all existing sessions on disk. 
        
        """
        ...
    
    @classmethod
    def load_bad_sessions_csv(cls, bad_sessions_csv_path=...): # -> tuple[DataFrame[Any], list[IdentifyingContext]]:
        """2024-09-23 - Load the "bad_sessions_table.csv" output by `IIDataMat_Export_ToPython_2022_08_01.m` (indicating sessions which failed to process at the MATLAB level for one reason or another)
        
        Usage:
            from neuropy.core.session.Formats.Specific.KDibaOldDataSessionFormat import KDibaOldDataSessionFormatRegisteredClass
            bad_sessions_csv_path = Path(r'~/repos/matlab-to-neuropy-exporter/output/2024-09-23_bad_sessions_table.csv').resolve() ## exported from `IIDataMat_Export_ToPython_2022_08_01.m`
            bad_session_df, bad_session_contexts = KDibaOldDataSessionFormatRegisteredClass.load_bad_sessions_csv(bad_sessions_csv_path=bad_sessions_csv_path)        
        """
        ...
    
    @classmethod
    def find_build_and_save_sessions_experiment_datetime_df_csv(cls, global_data_root_parent_path: Optional[Path] = ..., export_csv_path: Optional[Path] = ..., bad_sessions_csv_path: Optional[Path] = ...) -> Tuple[pd.DataFrame, Path]:
        """ discovers all existing sessions on disk and then exports a `sessions_experiment_datetime_df.csv` file containing information about the novelty and datetime of each session.
        
        Usage:
            from neuropy.core.session.Formats.Specific.KDibaOldDataSessionFormat import KDibaOldDataSessionFormatRegisteredClass
            
            sessions_df, export_folder_path = KDibaOldDataSessionFormatRegisteredClass.find_build_and_save_sessions_experiment_datetime_df_csv()
            
            sessions_df, export_folder_path = KDibaOldDataSessionFormatRegisteredClass.find_build_and_save_sessions_experiment_datetime_df_csv(export_folder_path=Path('EXTERNAL/PhoDibaPaper2024Book/EXTERNAL/sessions_experiment_datetime_df.csv').resolve(),
                                                                                        )
                
            sessions_df, export_folder_path = KDibaOldDataSessionFormatRegisteredClass.find_build_and_save_sessions_experiment_datetime_df_csv(global_data_root_parent_path=global_data_root_parent_path,
                                                                                        export_folder_path=Path('EXTERNAL/PhoDibaPaper2024Book/EXTERNAL/sessions_experiment_datetime_df.csv').resolve(),
            )
                                                                                    
            
        """
        ...
    
    @classmethod
    def perform_load_position_info_mat(cls, session_position_mat_file_path: Path, config_dict: Optional[Dict] = ..., debug_print: bool = ...) -> Dict:
        """ must conform to `[Path, DataSession], DataSession` """
        ...
    
    @classmethod
    def perform_load_position_info_mat_into_session(cls, session_position_mat_file_path: Path, session: DataSession, debug_print: bool = ...) -> DataSession:
        """ must conform to `[Path, DataSession], DataSession` """
        ...
    


