"""
This type stub file was generated by pyright.
"""

import param
from enum import Enum, unique
from typing import Any, Callable, Dict, List, Optional, Tuple
from attrs import field
from neuropy.core.parameters import BaseConfig

def keys_only_repr(instance): # -> str:
    """ specifies that this field only prints its .keys(), not its values.
    
    # Usage (within attrs class):
        computed_data: Optional[DynamicParameters] = serialized_field(default=None, repr=keys_only_repr)
        accumulated_errors: Optional[DynamicParameters] = non_serialized_field(default=Factory(DynamicParameters), is_computable=True, repr=keys_only_repr)
    
    """
    ...

@unique
class HDF_SerializationType(Enum):
    """ Specifies how a serialized field is stored, as an HDF5 Dataset or Attribute """
    DATASET = ...
    ATTRIBUTE = ...
    @property
    def required_tag(self): # -> Any:
        ...
    
    @classmethod
    def requiredClassTags(cls): # -> NDArray[Any]:
        ...
    


class AttrsBasedClassHelperMixin:
    """ heleprs for classes defined with `@define(slots=False, ...)` 
    
    from neuropy.utils.mixins.AttrsClassHelpers import AttrsBasedClassHelperMixin, custom_define


    hdf_fields = BasePositionDecoder.get_serialized_dataset_fields('hdf')

    """
    @classmethod
    def get_fields_with_tag(cls, tag: str = ..., invert: bool = ...) -> Tuple[List, Callable]:
        ...
    
    @classmethod
    def get_serialized_fields(cls, serializationType: HDF_SerializationType, serialization_format: str = ...) -> Tuple[List, Callable]:
        """ general function for getting the list of fields with a certain serializationType as a list of attrs attributes and a filter to select them useful for attrs.asdict(...) filtering. """
        ...
    
    @classmethod
    def get_serialized_dataset_fields(cls, serialization_format: str = ...) -> Tuple[List, Callable]:
        ...
    
    @classmethod
    def get_serialized_attribute_fields(cls, serialization_format: str = ...) -> Tuple[List, Callable]:
        ...
    
    def to_dict(self) -> Dict:
        ...
    


custom_define = ...
def merge_metadata(default_metadata: Dict[str, Any], additional_metadata: Optional[Dict[str, Any]]) -> Dict[str, Any]:
    ...

def non_serialized_field(default: Optional[Any] = ..., is_computable: bool = ..., metadata: Optional[Dict[str, Any]] = ..., **kwargs) -> field:
    ...

def serialized_field(default: Optional[Any] = ..., is_computable: bool = ..., serialization_fn: Optional[Callable] = ..., is_hdf_handled_custom: bool = ..., hdf_metadata: Optional[Dict] = ..., metadata: Optional[Dict[str, Any]] = ..., **kwargs) -> field:
    ...

def serialized_attribute_field(default: Optional[Any] = ..., is_computable: bool = ..., serialization_fn: Optional[Callable] = ..., metadata: Optional[Dict[str, Any]] = ..., **kwargs) -> field:
    """ marks a specific field to be serialized as an HDF5 attribute on the group for this object """
    ...

class SimpleFieldSizesReprMixin:
    """ Defines the __repr__ for implementors that only renders the implementors fields and their sizes

    from neuropy.utils.mixins.AttrsClassHelpers import SimpleFieldSizesReprMixin

    
    Prints something like:
    
        DecodedFilterEpochsResult(decoding_time_bin_size: float,
            filter_epochs: neuropy.core.epoch.Epoch,
            num_filter_epochs: int,
            most_likely_positions_list: list | shape (n_epochs),
            p_x_given_n_list: list | shape (n_epochs),
            marginal_x_list: list | shape (n_epochs),
            marginal_y_list: list | shape (n_epochs),
            most_likely_position_indicies_list: list | shape (n_epochs),
            spkcount: list | shape (n_epochs),
            nbins: numpy.ndarray | shape (n_epochs),
            time_bin_containers: list | shape (n_epochs),
            time_bin_edges: list | shape (n_epochs),
            epoch_description_list: list | shape (n_epochs)
        )

    for an attrs-based object
    
    """
    def __repr__(self): # -> str:
        """ 2024-01-11 - Renders only the fields and their sizes
        """
        ...
    


_default_class_name_dict_replace = ...
def convert_attrs_inline_class_instance_to_normal_class_defn(an_instance, class_name_replace_dict=..., print_output: bool = ...) -> str:
    """ Converts an inline `attrs`-based class definition generated via `attrs.make_class(...)` to a full-class-defn-form class definition.
    
     For example:
        ```python
        HeuristicScoresTuple = attrs.make_class("HeuristicScoresTuple", {k:field() for k in ("longest_sequence_length", "longest_sequence_length_ratio", "direction_change_bin_ratio", "congruent_dir_bins_ratio", "total_congruent_direction_change", 
                                                                                            "total_variation", "integral_second_derivative", "stddev_of_diff",
                                                                                            "position_derivatives_df")}, bases=(UnpackableMixin, object,))
        ```

        ```python
        class HeuristicScoresTuple(UnpackableMixin, object,):
            longest_sequence_length = field()
            longest_sequence_length_ratio = field()
            # ... remainder of fields
        ```


    Usage:

        from neuropy.utils.mixins.AttrsClassHelpers import convert_attrs_inline_class_instance_to_normal_class_defn
        content = convert_attrs_inline_class_instance_to_normal_class_defn(an_instance=deepcopy(active_heuristic_scores))
        print(content)
    
    """
    ...

class AttrsWithParamParameterizedHelpers:
    """ Helpers for programmatically modifying attrs-based classes to include param.Parameterized properties automatically so they can be used/edited/displayed in Param widgets
    

    from neuropy.utils.mixins.AttrsClassHelpers import AttrsWithParamParameterizedHelpers, BaseAttrsParameterizedParameters
    
    
    """
    attrs_to_params_type_map = ...
    @classmethod
    def attrs_to_parameters(cls, cls_to_decorate):
        ...
    
    @classmethod
    def attrs_to_parameters_with_fallback(cls, cls_to_decorate):
        ...
    
    @classmethod
    def attrs_to_parameters_container(cls, cls_to_decorate):
        """ all fields should be `param.Parameterized` subclasses """
        ...
    


class BaseAttrsParameterizedParameters(BaseConfig, param.Parameterized):
    """ Base class
    Based off of `BaseGlobalComputationParameters`
    
    """
    def __attrs_post_init__(self): # -> None:
        ...
    
    def __repr__(self): # -> str:
        """ 2024-01-11 - Renders only the fields and their sizes  """
        ...
    
    def values_only_repr(self, attr_separator_str: str = ..., sub_attr_additive_seperator_str: str = ...): # -> str:
        """ renders only the field names and their values
        
        _out_str: str = param_typed_parameters.values_only_repr(attr_separator_str=",\n", sub_attr_additive_seperator_str='\t')
        print(_out_str)

        """
        ...
    
    @classmethod
    def from_state(cls, state): # -> Self:
        """ Rebuilds an instance using the latest class definition and updates state. """
        ...
    
    def __setstate__(self, state): # -> None:
        """
        #TODO 2025-01-07 14:06: - [ ] UNFINISHED - needs to handle missing fields like 'should_disable_cache' added to one of the params types
            => these result in an `AttributeError: 'directional_decoders_decode_continuous_Parameters' object has no attribute 'should_disable_cache' when trying to pickle again after unpickling (`to_dict(...)`)
        
         Restore instance attributes and update child fields if needed. """
        ...
    
    @classmethod
    def get_class_param_Params_attribute_names(cls) -> List[str]:
        ...
    
    def get_param_Params_attribute_names(self) -> List[str]:
        ...
    
    @classmethod
    def get_class_param_Params_dict(cls, param_name_excludeList=...) -> Dict:
        ...
    
    def to_params_dict(self, param_name_excludeList=...) -> Dict:
        """ returns as a dictionary representation """
        ...
    


class BaseContainerAttrsParameterizedParametersToDictWidgetMixin:
    """ Provides an alternative/working way for a container to hold nested parameters since the normal way doesn't seem to work.

    import panel as pn
    pn.extension()

    curr_global_param_typed_parameters.display_params()
        

    """
    def get_param_Params_attribute_names(self) -> List[str]:
        ...
    
    def to_params_dict(self, param_name_excludeList=..., recursive_to_dict: bool = ...) -> Dict:
        """ overrides to provide recurrsive implementation
        returns as a dictionary representation 
        
        Working:
        
            out_configs_dict = curr_global_param_typed_parameters.to_params_dict(recursive_to_dict=False)
            pn.Column(*[pn.Param(a_sub_v) for a_sub_v in reversed(out_configs_dict.values())])

        """
        ...
    
    def display_params(self): # -> Column:
        """ renders the widget       
        Usage:
            import panel as pn
            pn.extension()

            curr_global_param_typed_parameters.display_params() 
        """
        ...
    


