"""
This type stub file was generated by pyright.
"""

import pandas as pd
from typing import Optional, Tuple

class PositionSlicedMixin:
    """ Used in Position-based classes to enable spatial filtering/slicing operations 
    
    from neuropy.utils.mixins.position_slicing import PositionSlicedMixin
    
    
    """
    @property
    def position_variable_names(self) -> Tuple[str, ...]:
        """ Returns tuple of position dimension column names ('x', 'y', 'z') """
        ...
    
    @property
    def binned_position_variable_names(self) -> Tuple[str, ...]:
        """ Returns tuple of binned position column names ('binned_x', 'binned_y') """
        ...
    
    def position_sliced(self, xmin: Optional[float] = ..., xmax: Optional[float] = ..., ymin: Optional[float] = ..., ymax: Optional[float] = ..., xmin_xmax_tuple: Optional[Tuple[float, float]] = ..., ymin_ymax_tuple: Optional[Tuple[float, float]] = ..., grid_bin_bounds: Optional[Tuple[Tuple[float, float], Tuple[float, float]]] = ...) -> pd.DataFrame:
        """ Returns a copy of the dataframe filtered to only include positions within the specified bounds """
        ...
    


